### ISSUE TITLE
US01: Cadastro do comprador - Front

### ISSUE THREAD

**Issue by freitasc** [mdsreq-fga-unb/2023.1-VenciNaPromo#11]
## Historia de Usuário
Eu, como usuário-comprador, desejo criar minha conta, adicionando minhas informações pessoais, como nome, endereço de e-mail e senha, para poder usufruir de descontos exclusivos em produtos perto do vencimento

## Critérios de Aceitação
- [x] O sistema deve ser capaz de criar uma conta para o usuário-comprador
- [x] O sistema deve ser guardar as informações pessoais, como nome, endereço de e-mail e senha
   - [x] O sistema deve checar por emails duplicados e invalidos
   - [x] O sistema deve checar por senhas fracas

## Prototipação
- [Tela A](URL do protótipo no figma)
- [Tela B](URL do protótipo no figma)
- [Tela C](URL do protótipo no figma)

**Comment by GabriellyAssuncao** [comment]
Concluído.
