### ISSUE TITLE
US02: Criar conta do vendedor - Front

### ISSUE THREAD

**Issue by freitasc** [mdsreq-fga-unb/2023.1-VenciNaPromo#12]
Eu, como usuário-vendedor, desejo criar minha conta, adicionando minhas informações pessoais, como nome, endereço de e-mail e senha, para poder aumentar minhas vendas e diminuir o desperdício dos meus alimentos perto do vencimento

## Critérios de Aceitação
- [x] O sistema deve ser capaz de criar uma conta para o usuário-vendedor
- [x] O sistema deve ser guardar as informações pessoais, como nome, endereço de e-mail e senha
   - [x] O sistema deve checar por emails duplicados e invalidos
   - [x] O sistema deve checar por senhas fracas

## Prototipação
- [Tela A](URL do protótipo no figma)
- [Tela B](URL do protótipo no figma)
- [Tela C](URL do protótipo no figma)

**Comment by GabriellyAssuncao** [comment]
Concluído.
