### ISSUE TITLE
US03: Autenticação do usuário-comprador - Front

### ISSUE THREAD

**Issue by freitasc** [mdsreq-fga-unb/2023.1-VenciNaPromo#13]
## Historia de Usuário
Eu, como usuário-comprador, desejo fazer login na minha conta utilizando meu endereço de e-mail e senha, para que eu possa gerar cupom exclusivos para os produtos selecionados no carrinho de compras

## Critérios de Aceitação
- [x] O sistema deve ser capaz de fazer autenticar o usuário-comprador
- [x] O sistema deve guardar o status de autenticação para futuros acessos (token no cache)

## Prototipação
- [Tela A](URL do protótipo no figma)
- [Tela B](URL do protótipo no figma)
- [Tela C](URL do protótipo no figma)

**Comment by GabriellyAssuncao** [comment]
Concluído.
