### ISSUE TITLE
US04: Autenticação do usuário-vendedor - Front

### ISSUE THREAD

**Issue by freitasc** [mdsreq-fga-unb/2023.1-VenciNaPromo#14]
## Historia de Usuário
Eu, como usuário-vendedor, desejo fazer login na minha conta utilizando meu endereço de e-mail e senha, para que eu possa disponibilizar seus produtos no site e visualizar o andamento das minhas vendas

## Critérios de Aceitação
- [x] O sistema deve ser capaz de fazer autenticar o usuário-vendedor
- [x] O sistema deve guardar o status de autenticação para futuros acessos (token no cache)

## Prototipação
- [Tela A](URL do protótipo no figma)
- [Tela B](URL do protótipo no figma)
- [Tela C](URL do protótipo no figma)

**Comment by GabriellyAssuncao** [comment]
Concluído.
