### ISSUE TITLE
US10: Lista de produtos - Front

### ISSUE THREAD

**Issue by freitasc** [mdsreq-fga-unb/2023.1-VenciNaPromo#16]
## Historia de Usuário
Eu, como usuário-comprador, desejo navegar pelos produtos disponíveis na lista de produtos cadastrados dentro do mercado on-line, para que eu possa acompanhar facilmente os produtos que estou interessado em comprar

## Critérios de Aceitação
- [ ] O sistema deve mostrar todos os produtos disponíveis na lista de produtos

## Prototipação
![US10: Lista de produtos](https://raw.githubusercontent.com/mdsreq-fga-unb/2023.1-VenciNaPromo/dev/ghpages/assets/images/documentacao/prototipo/descricao.png)

**Comment by charles-serafim** [comment]
Front end iniciado

**Comment by charles-serafim** [comment]
Commit - feature: us10 frontend
https://github.com/mdsreq-fga-unb/2023.1-VenciNaPromo/commit/d2bc7bc625c1b44e1a4f992c52e37305105e8126
