### ISSUE TITLE
Alterações no GitPages

### ISSUE THREAD

**Issue by sabrinaberno** [mdsreq-fga-unb/2023.1-VenciNaPromo#3]
- [ ] Adicionar requisitos na metodologia 
- [x] Descrever método de Sommerville na metodologia
- [ ] Descrever método de escolha do ScrumXP
- [x] Alterar o objetivo
- [ ] Adicionar quais serão as entregas das sprints no planejamento

**Comment by charles-serafim** [comment]
Adicionei mais dois tópicos na lista.

Updates:
-  Método de Sommerville e escolha da abordagem ágil descritos;
- Objetivo levemente alterado.
