### ISSUE TITLE
Adicionar textos explicativos

### ISSUE THREAD

**Issue by sabrinaberno** [mdsreq-fga-unb/2023.1-VenciNaPromo#40]
- [x] texto no mvp explicando como foi a definição do que seria escolhido em cada entrega 
- [x] texto explicando o que são URPS+ em requisitos não funcionais 
- [x] texto explicando qual foi o modelo para escrever as US que nós usamos
- [x] texto explicando qual foi o modelo para escrever os critérios de aceite das US que nós usamos

**Comment by GabriellyAssuncao** [comment]
concluído.
