### ISSUE TITLE
US13: Detalhes do produto - Front

### ISSUE THREAD

**Issue by sabrinaberno** [mdsreq-fga-unb/2023.1-VenciNaPromo#59]

**Comment by sabrinaberno** [comment]
## Historia de Usuário
Eu, como usuário-comprador, desejo visualizar os detalhes de um produto, incluindo título, descrição, vendedor do produto, local de retirada do produto, preço e disponibilidade, para que eu possa tomar uma decisão informada sobre a compra

## Critérios de Aceitação
- [ ] O sistema deve mostrar detalhes de cada produto
   - [ ] Os detalhes devem incluir título, descrição, vendedor do produto, local de retirada do produto, preço e disponibilidade

## Prototipação
- [Tela A](URL do protótipo no figma)
- [Tela B](URL do protótipo no figma)
- [Tela C](URL do protótipo no figma)

**Comment by charles-serafim** [comment]
Commit - feature: us13 frontend:
https://github.com/mdsreq-fga-unb/2023.1-VenciNaPromo/commit/75374dd3279d1bbe85dcaac13e1d0becea6f6d53
